server:
  port: 8100
spring:
  application:
    name: mcp-server-test
  ai:
    mcp:
      server:
        name: my-mcp-server
        version: 0.0.1
  alibaba:
    a2a:
      nacos:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: 88888888
        discovery:
          enabled: true # 启用 A2A 服务发现，用于发现远程智能体
        registry:
          enabled: true # 启用 Nacos Registry（需要 Nacos 3.x+）